import json


name = [
    {"sid": "id001", "name": "Subhamoy Karmakar", "Membership": "active"},
    {"sid": "id002", "name": "Sheenjini Ghosh", "Membership": "probation"},
    {"sid": "id003", "name": "Suman Haldar", "Membership": "active"},
    {"sid": "id004", "name": "Ananya Karmakar Haldar", "Membership": "probation"},
    {"sid": "id001", "name": "Subhamoy Karmakar", "Membership": "active"},
    {"sid": "id002", "name": "Sheenjini Ghosh", "Membership": "probation"},
    {"sid": "id003", "name": "Suman Haldar", "Membership": "active"},
    {"sid": "id004", "name": "Ananya Karmakar Haldar", "Membership": "probation"},
    {"sid": "id001", "name": "Subhamoy Karmakar", "Membership": "active"},
    {"sid": "id002", "name": "Sheenjini Ghosh", "Membership": "probation"},
    {"sid": "id003", "name": "Suman Haldar", "Membership": "active"},
    {"sid": "id004", "name": "Ananya Karmakar Haldar", "Membership": "probation"},
    {"sid": "id001", "name": "Subhamoy Karmakar", "Membership": "active"},
    {"sid": "id002", "name": "Sheenjini Ghosh", "Membership": "probation"},
    {"sid": "id003", "name": "Suman Haldar", "Membership": "active"},
    {"sid": "id004", "name": "Ananya Karmakar Haldar", "Membership": "probation"},
    {"sid": "id001", "name": "Subhamoy Karmakar", "Membership": "active"},
    {"sid": "id002", "name": "Sheenjini Ghosh", "Membership": "probation"},
    {"sid": "id003", "name": "Suman Haldar", "Membership": "active"},
    {"sid": "id004", "name": "Ananya Karmakar Haldar", "Membership": "probation"},
    {"sid": "id001", "name": "Subhamoy Karmakar", "Membership": "active"},
    {"sid": "id002", "name": "Sheenjini Ghosh", "Membership": "probation"},
    {"sid": "id003", "name": "Suman Haldar", "Membership": "active"},
    {"sid": "id004", "name": "Ananya Karmakar Haldar", "Membership": "probation"},
    {"sid": "id001", "name": "Subhamoy Karmakar", "Membership": "active"},
    {"sid": "id002", "name": "Sheenjini Ghosh", "Membership": "probation"},
    {"sid": "id003", "name": "Suman Haldar", "Membership": "active"},
    {"sid": "id004", "name": "Ananya Karmakar Haldar", "Membership": "probation"},
    {"sid": "id001", "name": "Subhamoy Karmakar", "Membership": "active"},
    {"sid": "id002", "name": "Sheenjini Ghosh", "Membership": "probation"},
    {"sid": "id003", "name": "Suman Haldar", "Membership": "active"},
    {"sid": "id004", "name": "Ananya Karmakar Haldar", "Membership": "probation"},
    {"sid": "id001", "name": "Subhamoy Karmakar", "Membership": "active"},
    {"sid": "id002", "name": "Sheenjini Ghosh", "Membership": "probation"},
    {"sid": "id003", "name": "Suman Haldar", "Membership": "active"},
    {"sid": "id004", "name": "Ananya Karmakar Haldar", "Membership": "probation"},
    {"sid": "id001", "name": "Subhamoy Karmakar", "Membership": "active"},
    {"sid": "id002", "name": "Sheenjini Ghosh", "Membership": "probation"},
    {"sid": "id003", "name": "Suman Haldar", "Membership": "active"},
    {"sid": "id004", "name": "Ananya Karmakar Haldar", "Membership": "probation"},
    {"sid": "id001", "name": "Subhamoy Karmakar", "Membership": "active"},
    {"sid": "id002", "name": "Sheenjini Ghosh", "Membership": "probation"},
    {"sid": "id003", "name": "Suman Haldar", "Membership": "active"},
    {"sid": "id004", "name": "Ananya Karmakar Haldar", "Membership": "probation"},
    {"sid": "id001", "name": "Subhamoy Karmakar", "Membership": "active"},
    {"sid": "id002", "name": "Sheenjini Ghosh", "Membership": "probation"},
    {"sid": "id003", "name": "Suman Haldar", "Membership": "active"},
    {"sid": "id004", "name": "Ananya Karmakar Haldar", "Membership": "probation"},
    {"sid": "id001", "name": "Subhamoy Karmakar", "Membership": "active"},
    {"sid": "id002", "name": "Sheenjini Ghosh", "Membership": "probation"},
    {"sid": "id003", "name": "Suman Haldar", "Membership": "active"},
    {"sid": "id004", "name": "Ananya Karmakar Haldar", "Membership": "probation"},
    {"sid": "id001", "name": "Subhamoy Karmakar", "Membership": "active"},
    {"sid": "id002", "name": "Sheenjini Ghosh", "Membership": "probation"},
    {"sid": "id003", "name": "Suman Haldar", "Membership": "active"},
    {"sid": "id004", "name": "Ananya Karmakar Haldar", "Membership": "probation"},
    {"sid": "id001", "name": "Subhamoy Karmakar", "Membership": "active"},
    {"sid": "id002", "name": "Sheenjini Ghosh", "Membership": "probation"},
    {"sid": "id003", "name": "Suman Haldar", "Membership": "active"},
    {"sid": "id004", "name": "Ananya Karmakar Haldar", "Membership": "probation"},
    {"sid": "id001", "name": "Subhamoy Karmakar", "Membership": "active"},
    {"sid": "id002", "name": "Sheenjini Ghosh", "Membership": "probation"},
    {"sid": "id003", "name": "Suman Haldar", "Membership": "active"},
    {"sid": "id004", "name": "Ananya Karmakar Haldar", "Membership": "probation"},
    {"sid": "id001", "name": "Subhamoy Karmakar", "Membership": "active"},
    {"sid": "id002", "name": "Sheenjini Ghosh", "Membership": "probation"},
    {"sid": "id003", "name": "Suman Haldar", "Membership": "active"},
    {"sid": "id004", "name": "Ananya Karmakar Haldar", "Membership": "probation"},
    {"sid": "id001", "name": "Subhamoy Karmakar", "Membership": "active"},
    {"sid": "id002", "name": "Sheenjini Ghosh", "Membership": "probation"},
    {"sid": "id003", "name": "Suman Haldar", "Membership": "active"},
    {"sid": "id004", "name": "Ananya Karmakar Haldar", "Membership": "probation"},
    {"sid": "id001", "name": "Subhamoy Karmakar", "Membership": "active"},
    {"sid": "id002", "name": "Sheenjini Ghosh", "Membership": "probation"},
    {"sid": "id003", "name": "Suman Haldar", "Membership": "active"},
    {"sid": "id004", "name": "Ananya Karmakar Haldar", "Membership": "probation"},
    {"sid": "id001", "name": "Subhamoy Karmakar", "Membership": "active"},
    {"sid": "id002", "name": "Sheenjini Ghosh", "Membership": "probation"},
    {"sid": "id003", "name": "Suman Haldar", "Membership": "active"},
    {"sid": "id004", "name": "Ananya Karmakar Haldar", "Membership": "probation"},
    {"sid": "id001", "name": "Subhamoy Karmakar", "Membership": "active"},
    {"sid": "id002", "name": "Sheenjini Ghosh", "Membership": "probation"},
    {"sid": "id003", "name": "Suman Haldar", "Membership": "active"},
    {"sid": "id004", "name": "Ananya Karmakar Haldar", "Membership": "probation"},
    {"sid": "id001", "name": "Subhamoy Karmakar", "Membership": "active"},
    {"sid": "id002", "name": "Sheenjini Ghosh", "Membership": "probation"},
    {"sid": "id003", "name": "Suman Haldar", "Membership": "active"},
    {"sid": "id004", "name": "Ananya Karmakar Haldar", "Membership": "probation"},
    {"sid": "id001", "name": "Subhamoy Karmakar", "Membership": "active"},
    {"sid": "id002", "name": "Sheenjini Ghosh", "Membership": "probation"},
    {"sid": "id003", "name": "Suman Haldar", "Membership": "active"},
    {"sid": "id004", "name": "Ananya Karmakar Haldar", "Membership": "probation"},
    {"sid": "id001", "name": "Subhamoy Karmakar", "Membership": "active"},
    {"sid": "id002", "name": "Sheenjini Ghosh", "Membership": "probation"},
    {"sid": "id003", "name": "Suman Haldar", "Membership": "active"},
    {"sid": "id004", "name": "Ananya Karmakar Haldar", "Membership": "probation"},
    {"sid": "id001", "name": "Subhamoy Karmakar", "Membership": "active"},
    {"sid": "id002", "name": "Sheenjini Ghosh", "Membership": "probation"},
    {"sid": "id003", "name": "Suman Haldar", "Membership": "active"},
    {"sid": "id004", "name": "Ananya Karmakar Haldar", "Membership": "probation"},
    {"sid": "id001", "name": "Subhamoy Karmakar", "Membership": "active"},
    {"sid": "id002", "name": "Sheenjini Ghosh", "Membership": "probation"},
    {"sid": "id003", "name": "Suman Haldar", "Membership": "active"},
    {"sid": "id004", "name": "Ananya Karmakar Haldar", "Membership": "probation"},
    {"sid": "id001", "name": "Subhamoy Karmakar", "Membership": "active"},
    {"sid": "id002", "name": "Sheenjini Ghosh", "Membership": "probation"},
    {"sid": "id003", "name": "Suman Haldar", "Membership": "active"},
    {"sid": "id004", "name": "Ananya Karmakar Haldar", "Membership": "probation"},
    {"sid": "id001", "name": "Subhamoy Karmakar", "Membership": "active"},
    {"sid": "id002", "name": "Sheenjini Ghosh", "Membership": "probation"},
    {"sid": "id003", "name": "Suman Haldar", "Membership": "active"},
    {"sid": "id004", "name": "Ananya Karmakar Haldar", "Membership": "probation"},
    {"sid": "id001", "name": "Subhamoy Karmakar", "Membership": "active"},
    {"sid": "id002", "name": "Sheenjini Ghosh", "Membership": "probation"},
    {"sid": "id003", "name": "Suman Haldar", "Membership": "active"},
    {"sid": "id004", "name": "Ananya Karmakar Haldar", "Membership": "probation"},
    {"sid": "id001", "name": "Subhamoy Karmakar", "Membership": "active"},
    {"sid": "id002", "name": "Sheenjini Ghosh", "Membership": "probation"},
    {"sid": "id003", "name": "Suman Haldar", "Membership": "active"},
    {"sid": "id004", "name": "Ananya Karmakar Haldar", "Membership": "probation"},
    {"sid": "id001", "name": "Subhamoy Karmakar", "Membership": "active"},
    {"sid": "id002", "name": "Sheenjini Ghosh", "Membership": "probation"},
    {"sid": "id003", "name": "Suman Haldar", "Membership": "active"},
    {"sid": "id004", "name": "Ananya Karmakar Haldar", "Membership": "probation"},
    {"sid": "id001", "name": "Subhamoy Karmakar", "Membership": "active"},
    {"sid": "id002", "name": "Sheenjini Ghosh", "Membership": "probation"},
    {"sid": "id003", "name": "Suman Haldar", "Membership": "active"},
    {"sid": "id004", "name": "Ananya Karmakar Haldar", "Membership": "probation"},
    {"sid": "id001", "name": "Subhamoy Karmakar", "Membership": "active"},
    {"sid": "id002", "name": "Sheenjini Ghosh", "Membership": "probation"},
    {"sid": "id003", "name": "Suman Haldar", "Membership": "active"},
    {"sid": "id004", "name": "Ananya Karmakar Haldar", "Membership": "probation"},
    {"sid": "id013", "name": "Chandan Mazumdar", "Membership": "expired"},
    {"sid": "id044", "name": "Sanjoy Kumar Saha", "Membership": "expired"},
]


# Returns all students data
def getAllStudentsList():
    return json.dumps(name, indent=4)


# Returns student dat queried by search term
def getFilteredResult(queryText):
    res = []
    queryText = str(queryText).lower()
    for n in name:
        for k in n.keys():
            if str(n[k]).lower().__contains__(queryText):
                res.append(n)
                break

    return json.dumps(res, indent=4)
