# FIREBASE
FB_DB_URL = 'https://gymbuddyall.firebaseio.com/'
FB_GROUP_NAME = 'gymbuddyall/'

FB_TABLE_STUDENTS = 'Students'
FB_KEY_STUDENTS_SID = 'SID'
FB_KEY_STUDENTS_ALLOTED_TIME = 'allotedtime'
FB_KEY_STUDENTS_MEMBERSHIP = 'membershipvalidity'
FB_KEY_STUDENTS_PHONE = 'phone'
FB_KEY_STUDENTS_AGE = 'studentage'
FB_KEY_STUDENTS_NAME = 'studentname'

FB_TABLE_ADMIN = 'Notification'
FB_KEY_NOTIFICATION_NID = 'notifId'
FB_KEY_NOTIFICATION_SID = 'studentId'
FB_KEY_NOTIFICATION_DATETIME = 'dateTime'
FB_KEY_NOTIFICATION_LEVEL = 'level'
FB_KEY_NOTIFICATION_MSG = 'msg'

FB_TABLE_ADMIN = 'GymAdmin'
FB_KEY_ADMIN_ID = 'gymId'
FB_KEY_ADMIN_NAME = 'gymName'
FB_KEY_ADMIN_NAME = 'adminName'
FB_KEY_ADMIN_PHONE = 'phone'
FB_KEY_ADMIN_VALIDITY = 'validity'
FB_KEY_ADMIN_USERNAME = 'username'
FB_KEY_ADMIN_PASSWD = 'passwd'
FB_KEY_ADMIN_STATUS = 'loginstatus'
